config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users

  resources :exercises, only: [:show, :new, :create, :index, :destroy, :edit, :update] do
    collection do
      post :add_existing
      get :strength_log
      delete :bulk_delete_selected
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :exercises  # この行を追加
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
    @start_date = @date.beginning_of_month.beginning_of_week(:sunday) 
    @end_date = @date.end_of_month.end_of_week(:sunday) 
  
    # 特定ユーザーのトレーニングのみを取得
    month_exercises = Exercise.where(user: @user, date: @start_date..@end_date)
    @training_days = month_exercises.group_by { |e| e.date.to_date }.transform_values(&:count) 
  
    # トレーニング部位のリストを取得
    @parts = Exercise.select(:part).distinct.pluck(:part)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    # paramsハッシュからユーザーを取得します。
    def set_user
      @user = User.find(params[:id])
    end

    # ログイン済みのユーザーか確認します。
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end
    
    # アクセスしたユーザーが現在ログインしているユーザーか確認します。
    def correct_user
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, data: { turbo: false }) do |f| %>
  <div class="user-registration-container"> <!-- コンテナで囲む -->
    <%= render 'shared/error_messages', object: @user %>

    <%= f.label :name, class: "label-signup" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :email, class: "label-signup" %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :password, class: "label-signup" %>
    <%= f.password_field :password, class: "form-control" %>

    <%= f.label :password_confirmation, class: "label-signup" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>

    <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
  </div> <!-- コンテナの終了 -->
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<div class="user-edit-background">  
  <div class="user-edit-container">  
    <h1 class="user-info-title">ユーザー情報の更新</h1>
    
    <div class="user-label-container">
      <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<div class="signup-page-background">
  <div class="form-background">
    <!-- 内側のコンテンツを包む新しいdivを追加 -->
    <div class="form-content-padding">
      <div class="text-right-align">
        <h1 class="highlight-text">ユーザー登録</h1>
        <div class="row">
          <div class="col-md-6 col-md-offset-3 form-custom-width">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="background-calendar">
  <div class="calendar-navigation">
    <%= link_to '◀', user_path(@user, month: @date.prev_month), class: 'nav-arrow' %>
    <span class="month-year"><%= @date.strftime("%Y年 %m月") %></span>
    <%= link_to '▶', user_path(@user, month: @date.next_month), class: 'nav-arrow' %>
  </div>
  
  <div class="calendar">
    <!-- 曜日のヘッダー -->
    <% %w[日 月 火 水 木 金 土].each do |day| %>
      <div class="day-header"><%= day %></div>
    <% end %>
  
    <!-- 月の日付 -->
    <% (@start_date..@end_date).each do |date| %>
      <%= link_to exercises_path(date: date), class: 'calendar-date-link' do %>
        <div class="<%= 'day' %> <%= 'today' if date == Date.today %> <%= 'not-current-month' unless date.month == @date.month %> <%= 'training-day' if @training_days[date] && @training_days[date] > 0 %>">
          <%= date.day %>
          <% if @training_days[date] && @training_days[date] > 0 %>
            <span class="training-dot">●</span>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>